# Site settings
title: UTA Engineering Student Council
description: UT Arlington's Engineering Student Council organization website.

helplinks:
  - MavOrgs Page: https://mavorgs.collegiatelink.net/organization/esc
  - College of Engineering: http://www.uta.edu/engineering/
  - Facebook Page: https://www.facebook.com/UTAESC

infoblocks:
  General UTA Info: |
    University of Texas at Arlington <br/>
    701 S. Nedderman Drive <br/>
    Arlington, TX 76019

gCalId: nqq4mcf674on24nt0439v10c0k%40group.calendar.google.com
gCalKey: AIzaSyDbnuof_VHqnMtlWKm3KGjDmi-VOJ8uK4Q
